name: Scrape Letterboxd

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

concurrency:
  group: scrape
  cancel-in-progress: false

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py

    - name: Build TMDB cache
      run: python build_tmdb_cache.py
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git pull
        git add -A docs/ state.txt cache_state.txt
        git commit -m "Update cache" || true
        git push
